### PR TITLE
Removes project specific things, cleanup

### PR DESCRIPTION
**Pull request by sbrunner**
Simple alternate of #6 

To test in the ECA project add in the docker-compse file:
```yaml
command: ["/mapcache/start"]
```
And create a file named `mapcache/start` with:
```bash
#!/bin/bash -e

chown -R www-data: /var/sig/tiles
apache2ctl -DFOREGROUND
```

### CODE REVIEW

**Review by yjacolin — APPROVED** [review]

**Comment by yjacolin** [comment]
mapcache/start file seems not useful in ECA. docker-compose failed with entrypoint items (`ERROR: for ecawebservice_mapcache_1  Cannot start service mapcache: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/mapcache/start\": stat /mapcache/start: no such file or directory": unknown`)

**Comment by sbrunner** [comment]
I just update the fir st message by replacing entrypoint by command, and exec ... by `apache2ctl -DFOREGROUND`, and for me it's working...

**Comment by sbrunner** [comment]
Do you try to do a `docker-compose down`?

**Comment by yjacolin** [comment]
I started from scratch.

**Comment by yjacolin** [comment]
Ok it worked with command option but I think it should work with entry-point also but I can't test it as you changed your comment and I don't remember some part of it. Do you want that I test also with entry-point in docker-compose?

The issue came from the config image docker was not uptodate and the mapcache/start script was missing!

[Edit]
Tested with success with entrypoint in docker-compose and exec $0 in mapcache/start script instead of apachectl.

**Comment by sbrunner** [comment]
Hello,

I had this:
```yaml
entrypoint: ["/mapcache/start"]
```
```bash
#!/bin/bash -e

chown -R www-data: /var/sig/tiles
exec "$@"
```

But I don't succeed to make it working and @pvalsecc isn't fan of entrypoint...

**Review by pvalsecc — APPROVED** [review]

**Pull request merged**
